name: Close Pull Request

on:
  pull_request:
    types: [ opened, reopened ]

jobs:
  check_pull_requst:

    name: Close if test not passed

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: chmod +x mvnw && ./mvnw clean package

      - uses: superbrothers/close-pull-request@v3
        if: ${{ failure() }}
        with:
          comment: "Test or build not passed."
          github_token: ${{ secrets.TOKEN_GITHUB }}