name: Test & Deploy

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: mesages-api
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }}

jobs:
  deploy:

    name: Test & Deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: chmod +x mvnw && ./mvnw clean package

      - name: 'Deploy to Azure'
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/target/*.jar'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

